path:
  dataset:
    images: 'data/images/'
    csv: 'data/csv/metadata.csv'
    preprocessed: 'data/preprocessed/'
  model_dir:
    weights: 'models/weights/'
    performance: 'models/performance/'
  visualisations:
    heatmaps: 'visualisations/heatmaps/'
    plots: 'visualisations/plots/'
    tables: 'visualisations/tables/'

training:
  batch_size: 16
  learning_rate: 0.001
  num_epochs: 5
  num_workers: 0
  k_folds: 5
  alpha: 0.001

misc:
  headers: ['Model', 'Precision', 'Recall', 'F1 Score', 'AUC Score']
  random_seed: 44
